### ISSUE TITLE
Can't create a new webolg

### ISSUE THREAD

**Issue by Darkseid1981** [pivotx/PivotX#4]
I am really sorry, I know you just fix one issue and now I'm adding another. I don't want to be a nuisance, but could you possibly help with this, I want to experiment working with more than one weblog but I get a blank page after clicking on the "New Weblog" button.  It's the same on the Free Webhost (I'll just refer to them as Byethost, as that's where I'm hosting my blog.) I looked at the PHP_error_log on my laptop and saw this

PHP_error_log
`[30-May-2023 13:29:49 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function themeList(), 0 passed in /opt/lampp/htdocs/projects/pivotx-3/pivotx/forms.php on line 1308 and exactly 1 expected in /opt/lampp/htdocs/projects/pivotx-3/pivotx/lib.php:1685
Stack trace:
#0 /opt/lampp/htdocs/projects/pivotx-3/pivotx/forms.php(1308): themeList()
#1 /opt/lampp/htdocs/projects/pivotx-3/pivotx/pages.php(1992): getNewWeblogForm()
#2 /opt/lampp/htdocs/projects/pivotx-3/pivotx/lib.php(272): pageWeblognew()
#3 /opt/lampp/htdocs/projects/pivotx-3/pivotx/index.php(21): displayPage()
#4 {main}
    thrown in /opt/lampp/htdocs/projects/pivotx-3/pivotx/lib.php on line 1685
`
What does that mean and how do I fix it. I'm more than willing to try and fix this my self, if someone can tell me how, or paste the fix here and then tell where every thing goes.

Please and Thank you.

**Comment by hansfn** [comment]
No reason to be sorry. I have implicitly made a promise to keep PivotX working for PHP 8 and I don't mind keeping that promise. Fix coming shortly.

**Comment by hansfn** [comment]
Fixed - see [this commit](https://github.com/pivotx/PivotX/commit/b6f157c13e4b7fadfee29c3b3b8e8930b1edb2fc) or download the zip file again.

PS! PivotX is old PHP code and should in general not be studied. I still think PivotX is great in many ways, but not as a starting point for learning modern PHP.

**Comment by Darkseid1981** [comment]
Sorry for the confusion, I'm not studying PivotX to learn PHP, I've got a book for that. I just meant that if I ever get through with my studies that I would try and help with maintaining PivotX as best I can. If I ever get good at it I might even try a major upgrade or even overhaul project.
